IDIR =./src/include
CC=gcc
CFLAGS=-I$(IDIR)

ODIR=build
LDIR =./lib

LIBS=-lm

_DEPS = talib-cli.h
DEPS = $(patsubst %,$(IDIR)/%,$(_DEPS))

_OBJ = talib-cli.o
OBJ = $(patsubst %,$(ODIR)/%,$(_OBJ))


$(ODIR)/%.o: %.c $(DEPS)
  $(CC) -c -o $@ $< $(CFLAGS)

talib-cli: $(OBJ)
  gcc -o $@ $^ $(CFLAGS) $(LIBS)

.PHONY: clean

clean:
  rm -f $(ODIR)/*.o *~ core $(INCDIR)/*~